
package View;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class facturacheckout extends javax.swing.JFrame implements Printable{
    
    public static void main (String[] args){
        double a = (int) (Math.random() * 123 + 14 );
    }

    /**
     * Creates new form facturacheckout
     */
    public facturacheckout() {
        initComponents();
        fechaactual.setText(fecha());
        this.setTitle("factura");
        this.setLocationRelativeTo(null);
        
        Panelcheckout factura = new Panelcheckout();
        textohuesped.setText(factura.textofacturahuesped);
        textotelefono.setText(factura.textofacturatelefono);
        textoingreso.setText(factura.textofacturaingreso);
        textosalida.setText(factura.textofacturasalida);
        textohabitacion.setText(factura.textofacturahabitacion);
        textovalor.setText(factura.textofacturavalor);
        textoid.setText(factura.textofacturaid);
        Random rand = new Random();
        int randomNumber = rand.nextInt(100) + 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        factura = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textohuesped = new javax.swing.JLabel();
        textotelefono = new javax.swing.JLabel();
        textohabitacion = new javax.swing.JLabel();
        textosalida = new javax.swing.JLabel();
        textoingreso = new javax.swing.JLabel();
        fechaactual = new javax.swing.JLabel();
        textovalor = new javax.swing.JLabel();
        textoid = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnimprimir = new javax.swing.JButton();
        Imprimir = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setMinimumSize(new java.awt.Dimension(641, 577));

        factura.setBackground(new java.awt.Color(255, 255, 255));
        factura.setForeground(new java.awt.Color(102, 102, 102));
        factura.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 1, 16)); // NOI18N
        jLabel4.setText("Cliente:");
        factura.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 1, 16)); // NOI18N
        jLabel6.setText("Recibo #");
        factura.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 1, 16)); // NOI18N
        jLabel9.setText("Fecha de factura:");
        factura.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        jLabel11.setFont(new java.awt.Font("Bookman Old Style", 1, 16)); // NOI18N
        jLabel11.setText("Fecha de ingreso:");
        factura.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jLabel12.setFont(new java.awt.Font("Bookman Old Style", 1, 16)); // NOI18N
        jLabel12.setText("Fecha salida:");
        factura.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jLabel17.setFont(new java.awt.Font("Bookman Old Style", 1, 16)); // NOI18N
        jLabel17.setText("Habitacion:");
        factura.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel19.setText("Nit");
        factura.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));
        factura.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        textohuesped.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textohuesped.setText("jLabel3");
        factura.add(textohuesped, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        textotelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textotelefono.setText("jLabel7");
        factura.add(textotelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        textohabitacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textohabitacion.setText("jLabel10");
        factura.add(textohabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        textosalida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textosalida.setText("jLabel14");
        factura.add(textosalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, -1, -1));

        textoingreso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoingreso.setText("jLabel10");
        factura.add(textoingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, -1, 20));

        fechaactual.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fechaactual.setText("jLabel10");
        factura.add(fechaactual, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, -1));

        textovalor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textovalor.setText("Valor:");
        factura.add(textovalor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        textoid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoid.setText("Id:");
        factura.add(textoid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 20, -1));

        jLabel10.setFont(new java.awt.Font("Bookman Old Style", 1, 16)); // NOI18N
        jLabel10.setText("Telefono:");
        factura.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel13.setFont(new java.awt.Font("Bookman Old Style", 1, 16)); // NOI18N
        jLabel13.setText("Valor:");
        factura.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel2.setText("999.999");
        factura.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/file (2).png"))); // NOI18N
        jLabel3.setText("jLabel3");
        factura.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 280, 60));

        btnimprimir.setBackground(new java.awt.Color(21, 95, 130));
        btnimprimir.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        btnimprimir.setForeground(new java.awt.Color(255, 255, 255));
        btnimprimir.setText("Imprimir");
        btnimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimirActionPerformed(evt);
            }
        });

        Imprimir.setBackground(new java.awt.Color(21, 95, 130));
        Imprimir.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        Imprimir.setForeground(new java.awt.Color(255, 255, 255));
        Imprimir.setText("Salir");
        Imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnimprimir)
                .addGap(34, 34, 34)
                .addComponent(Imprimir)
                .addGap(19, 19, 19))
            .addComponent(factura, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(factura, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ImprimirActionPerformed

    private void btnimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimirActionPerformed
        try {
            PrinterJob gap = PrinterJob.getPrinterJob();
            gap.setPrintable(this);
            boolean top = gap.printDialog();
            if(top){
                gap.print();
            }
            
        } catch (PrinterException pex) {
            JOptionPane.showMessageDialog(null, "error de programa", "error" + pex, JOptionPane.INFORMATION_MESSAGE);
        }
      
 
    }//GEN-LAST:event_btnimprimirActionPerformed

  public  static String fecha(){
      Date fecha = new Date();
      SimpleDateFormat formato = new SimpleDateFormat("dd/MM/YYYY");
      return formato.format(fecha);
  }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Imprimir;
    private javax.swing.JButton btnimprimir;
    private javax.swing.JPanel factura;
    private javax.swing.JLabel fechaactual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel textohabitacion;
    private javax.swing.JLabel textohuesped;
    private javax.swing.JLabel textoid;
    private javax.swing.JLabel textoingreso;
    private javax.swing.JLabel textosalida;
    private javax.swing.JLabel textotelefono;
    private javax.swing.JLabel textovalor;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graf, PageFormat pagfor, int index) throws PrinterException {
        if (index>0) {
            return NO_SUCH_PAGE;
            
        }
        Graphics2D hub = (Graphics2D) graf;
        hub.translate(pagfor.getImageableX() + 30, pagfor.getImageableY() + 30);
        hub.scale(0.85, 0.85);
        
        factura.printAll(graf);
        return PAGE_EXISTS;
        
    }
}
