package View;

import Model.Servicio;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;

import java.net.URISyntaxException;
import java.time.LocalDate;


public class FormMain extends javax.swing.JFrame {

    public FormMain() {
        initComponents();
        this.setTitle("App Hotel CheckEasy");
        Image icono = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/icono_checkeasy.jpg"));        
        this.setIconImage(icono);
        this.setLocationRelativeTo(null);
        PanelPrincipal.setVisible(true); 
        
        System.out.println("inicializa menu principal");                    
        LocalDate now = LocalDate.now();
        int year = now.getYear();
        int dia = now.getDayOfMonth();
        int month = now.getMonthValue();
        String[] meses = {"Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto"," ;Septiembre"
            ,"Octubre","Noviembre","Diciemrbre"};
        
        fecha.setText("Hoy es  " + dia+" de "+ meses[month - 1] + " de "+year);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        PanelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuPrincipal = new javax.swing.JMenuItem();
        menuConfig = new javax.swing.JMenu();
        menuUsers = new javax.swing.JMenuItem();
        menurooms = new javax.swing.JMenuItem();
        menusalir = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuchekin = new javax.swing.JMenuItem();
        menutakealook = new javax.swing.JMenuItem();
        menucheckout = new javax.swing.JMenuItem();
        menuCancel = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuweb = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("App Hotel CheckEasy");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        content.setPreferredSize(new java.awt.Dimension(717, 517));
        content.setRequestFocusEnabled(false);

        PanelPrincipal.setBackground(new java.awt.Color(234, 234, 213));
        PanelPrincipal.setPreferredSize(new java.awt.Dimension(516, 465));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo_checkeasy2.jpg"))); // NOI18N

        fecha.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        fecha.setForeground(new java.awt.Color(0, 102, 255));
        fecha.setText("Hoy es .....");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/main.png"))); // NOI18N

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(fecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(129, 129, 129))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62)
                .addComponent(jLabel3)
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contentLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contentLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        menuArchivo.setText("Archivo");
        menuArchivo.add(jSeparator1);

        menuPrincipal.setText("Principal");
        menuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPrincipalActionPerformed(evt);
            }
        });
        menuArchivo.add(menuPrincipal);

        menuConfig.setText("Configurar");

        menuUsers.setText("Usuarios");
        menuUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsersActionPerformed(evt);
            }
        });
        menuConfig.add(menuUsers);

        menurooms.setText("Habitaciones");
        menurooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuroomsActionPerformed(evt);
            }
        });
        menuConfig.add(menurooms);

        menuArchivo.add(menuConfig);

        menusalir.setText("Salir");
        menusalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menusalirActionPerformed(evt);
            }
        });
        menuArchivo.add(menusalir);

        jMenuBar1.add(menuArchivo);

        jMenu1.setText("Procesos");
        jMenu1.add(jSeparator2);

        menuchekin.setText("Check in/Reserva");
        menuchekin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuchekinActionPerformed(evt);
            }
        });
        jMenu1.add(menuchekin);

        menutakealook.setText("Consulta");
        menutakealook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menutakealookActionPerformed(evt);
            }
        });
        jMenu1.add(menutakealook);

        menucheckout.setText("CheckOut");
        menucheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menucheckoutActionPerformed(evt);
            }
        });
        jMenu1.add(menucheckout);

        menuCancel.setText("Cancelar Reserva");
        menuCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCancelActionPerformed(evt);
            }
        });
        jMenu1.add(menuCancel);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Web");
        jMenu2.add(jSeparator3);

        menuweb.setText("Pagina Web");
        menuweb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuwebActionPerformed(evt);
            }
        });
        jMenu2.add(menuweb);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


 
    private void menusalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menusalirActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        //System.exit(0);
        this.dispose();
        
    }//GEN-LAST:event_menusalirActionPerformed

    private void menuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPrincipalActionPerformed
        // TODO add your handling code here:
        this.setTitle("App Hotel CheckEasy  -  Principal");        
        Panelmain page = new Panelmain();
        Servicio servicios =new Servicio();
        servicios.ShowPanel(page, content);
        

    }//GEN-LAST:event_menuPrincipalActionPerformed
    private void goToURL(String URL){
           if (java.awt.Desktop.isDesktopSupported()) {
            java.awt.Desktop desktop = java.awt.Desktop.getDesktop();
 
            if (desktop.isSupported(java.awt.Desktop.Action.BROWSE)) {
                try {
                    java.net.URI uri = new java.net.URI(URL);
                    desktop.browse(uri);
                } catch (URISyntaxException | IOException ex) {
                    //Logger.getLogger(Acerca.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }
    private void menuUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsersActionPerformed
        // TODO add your handling code here:
        this.setTitle("App Hotel CheckEasy  -  Configurar Usuarios");        
        PanelUsers page = new PanelUsers();
        Servicio servicios =new Servicio();
        servicios.ShowPanel(page, content);      
    }//GEN-LAST:event_menuUsersActionPerformed

    private void menuroomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuroomsActionPerformed
        // TODO add your handling code here:
        this.setTitle("App Hotel CheckEasy  -  Configurar Habitaciones");                
        PanelRooms page = new PanelRooms();
        Servicio servicios =new Servicio();
        servicios.ShowPanel(page, content);
       
    }//GEN-LAST:event_menuroomsActionPerformed

    private void menuchekinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuchekinActionPerformed
        // TODO add your handling code here:
                    
        PanelCheckin page = new PanelCheckin();
        Servicio servicios =new Servicio();
        servicios.IniciaCheckInReserva( "App Hotel CheckEasy  -  Check in / Resevas" ,this, page , content );        
    }//GEN-LAST:event_menuchekinActionPerformed

    private void menutakealookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menutakealookActionPerformed
        // TODO add your handling code here:
        
        Paneltakealook  page = new Paneltakealook();
        Servicio servicios =new Servicio();
        servicios.IniciaConsultaderegistros("App Hotel CheckEasy  -  Consultas", this, page, content);
 
    }//GEN-LAST:event_menutakealookActionPerformed

    private void menucheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menucheckoutActionPerformed
        // TODO add your handling code here:
       
        Panelcheckout  page = new Panelcheckout();
        Servicio servicios =new Servicio();
        servicios.IniciaCheckout("App Hotel CheckEasy  -  Check Out", this, page, content);
        
    }//GEN-LAST:event_menucheckoutActionPerformed

    private void menuwebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuwebActionPerformed
        // TODO add your handling code here:
          goToURL("https://hotelsantabarbarareal.com/");
    }//GEN-LAST:event_menuwebActionPerformed

    private void menuCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCancelActionPerformed
        // TODO add your handling code here:      
        Panelcancel  page = new Panelcancel();
        Servicio servicios =new Servicio();
        servicios.IniciaCancelarReserva( "App Hotel Cancelar Reserva",this ,page ,content );
      
    }//GEN-LAST:event_menuCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel content;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuItem menuCancel;
    private javax.swing.JMenu menuConfig;
    private javax.swing.JMenuItem menuPrincipal;
    private javax.swing.JMenuItem menuUsers;
    private javax.swing.JMenuItem menucheckout;
    private javax.swing.JMenuItem menuchekin;
    private javax.swing.JMenuItem menurooms;
    private javax.swing.JMenuItem menusalir;
    private javax.swing.JMenuItem menutakealook;
    private javax.swing.JMenuItem menuweb;
    // End of variables declaration//GEN-END:variables
}
