
package View;
import Model.Servicio;
import Model.UserEmploy;
import java.sql.SQLException;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class PanelUsers extends javax.swing.JPanel {
            
    public PanelUsers() {
        initComponents();
                       
        FillTableUsers();
             
        txtusuario.requestFocus();
    }

    private boolean ExisteUsuario (){
        boolean valida = false;
        for (int i = 0; i < Tablausuarios.getRowCount(); i++) {
            if (Tablausuarios.getValueAt(i, 0).equals(txtusuario.getText()) ){
                valida = true;
                break;
            }    
        }
        return valida;
    }   
    private void FillTableUsers(){
        Servicio objusuarios = new Servicio();
        List<UserEmploy> usuarios = objusuarios.ConsultarUsuarios();
        var model = (DefaultTableModel) Tablausuarios.getModel();
        limpiarTabla();
        for(UserEmploy obj: usuarios){
            model.addRow(new Object[]{
                obj.getUsuario(), obj.getNombre(), obj.getCorreo(),obj.getTelefono()
            });
        }

    }
    private void limpiarTabla(){
         DefaultTableModel model = (DefaultTableModel) Tablausuarios.getModel();    
        while (Tablausuarios.getRowCount() >0){
            model.removeRow(0);
        }
    }    
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PageConfig = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        lblcorreo = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        lbltelefono = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        lblpass = new javax.swing.JLabel();
        txtpass = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        bntInsertar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tablausuarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(717, 517));

        PageConfig.setBackground(new java.awt.Color(234, 234, 213));
        PageConfig.setPreferredSize(new java.awt.Dimension(516, 465));
        PageConfig.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PageConfigFocusGained(evt);
            }
        });
        PageConfig.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(234, 234, 213));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(234, 234, 213));

        lblUsuario.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        lblUsuario.setText("Usuario");

        txtusuario.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        txtusuario.setForeground(new java.awt.Color(102, 102, 102));
        txtusuario.setToolTipText("maximo 8 caracteres");
        txtusuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });
        txtusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtusuarioKeyTyped(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        lblNombre.setText("Nombre");

        txtnombre.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        txtnombre.setForeground(new java.awt.Color(102, 102, 102));
        txtnombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });

        lblcorreo.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        lblcorreo.setText("Correo");

        txtcorreo.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        txtcorreo.setForeground(new java.awt.Color(102, 102, 102));
        txtcorreo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcorreoActionPerformed(evt);
            }
        });

        lbltelefono.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        lbltelefono.setText("Telefono");

        txttelefono.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        txttelefono.setForeground(new java.awt.Color(102, 102, 102));
        txttelefono.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txttelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefonoActionPerformed(evt);
            }
        });
        txttelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelefonoKeyTyped(evt);
            }
        });

        lblpass.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        lblpass.setText("Clave");

        txtpass.setBackground(new java.awt.Color(204, 204, 204));
        txtpass.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        txtpass.setForeground(new java.awt.Color(102, 102, 102));
        txtpass.setText("123");
        txtpass.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtpass.setEnabled(false);
        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblUsuario)
                            .addGap(9, 9, 9)
                            .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblNombre)
                            .addGap(18, 18, 18)
                            .addComponent(txtnombre))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(lblcorreo)
                            .addGap(6, 6, 6)
                            .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbltelefono)
                            .addGap(13, 13, 13)
                            .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblpass)
                        .addGap(14, 14, 14)
                        .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 415, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuario)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNombre))
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcorreo)
                    .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltelefono)
                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblpass)
                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        PageConfig.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 610, 120));

        btnActualizar.setBackground(new java.awt.Color(21, 95, 130));
        btnActualizar.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        PageConfig.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 80, 40));

        btnLimpiar.setBackground(new java.awt.Color(21, 95, 130));
        btnLimpiar.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        PageConfig.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 80, 40));

        bntInsertar.setBackground(new java.awt.Color(21, 95, 130));
        bntInsertar.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        bntInsertar.setForeground(new java.awt.Color(255, 255, 255));
        bntInsertar.setText("Agregar");
        bntInsertar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntInsertarActionPerformed(evt);
            }
        });
        PageConfig.add(bntInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 70, 40));

        btnBorrar.setBackground(new java.awt.Color(21, 95, 130));
        btnBorrar.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/borrar.png"))); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        PageConfig.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, -1, -1));

        Tablausuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario", "Nombre", "Correo", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tablausuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablausuariosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Tablausuarios);

        PageConfig.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 630, 220));
        PageConfig.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 130, 70));

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 102, 255));
        titulo.setText("Configurar Usuarios del Sistema");
        PageConfig.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PageConfig, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PageConfig, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuarioActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreoActionPerformed

    private void txttelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefonoActionPerformed

    private void bntInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntInsertarActionPerformed
        // TODO add your handling code here:
        if (txtnombre.getText().isEmpty() || txtusuario.getText().isEmpty() || txtcorreo.getText().isEmpty() || txttelefono.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese todos los campos. Intente de nuevo","Informacion", JOptionPane.INFORMATION_MESSAGE);            
        }            
        else {
            if (!ExisteUsuario()){            
                int ninteger = Integer.parseInt(txttelefono.getText());
                UserEmploy p5 = new UserEmploy (txtusuario.getText(),"123",txtnombre.getText(), txtcorreo.getText(), ninteger);
                try {
                    p5.CrearUsuario();
                } catch (SQLException ex) {
                    Logger.getLogger(PanelUsers.class.getName()).log(Level.SEVERE, null, ex);
                }
                //adiciona a la tabla
                DefaultTableModel model = (DefaultTableModel) Tablausuarios.getModel();
                model.addRow(new Object[]{p5.getUsuario(),p5.getNombre(), p5.getCorreo(), p5.getTelefono()});            
                txtnombre.setText("");
                txtusuario.setText("");
                txtcorreo.setText("");
                txttelefono.setText("");
                JOptionPane.showMessageDialog(null, "Usuario Insertado","Informacion", JOptionPane.INFORMATION_MESSAGE);                                                                            
            }
            else{
                JOptionPane.showMessageDialog(null, "Usuario ya existe","Informacion", JOptionPane.INFORMATION_MESSAGE);                                                        
            }
        }
        
    }//GEN-LAST:event_bntInsertarActionPerformed


    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:

        int row = Tablausuarios.getSelectedRow();
        if (row <0){
            JOptionPane.showMessageDialog(null, "Por favor seleccione una Fila","Informacion", JOptionPane.INFORMATION_MESSAGE);                        
        }
        else
        {
            if (ExisteUsuario()){
                int ninteger = Integer.parseInt(txttelefono.getText());
                UserEmploy p5 = new UserEmploy (txtusuario.getText(),"",txtnombre.getText(), txtcorreo.getText(), ninteger);
                try {
                    p5.ActualizarUsuario();
                } catch (SQLException ex) {
                    Logger.getLogger(PanelUsers.class.getName()).log(Level.SEVERE, null, ex);
                }
                FillTableUsers();                    
                txtnombre.setText("");
                txtusuario.setText("");
                txtcorreo.setText("");
                txttelefono.setText("");
                JOptionPane.showMessageDialog(null, "Uusario Actualizado","Informacion", JOptionPane.INFORMATION_MESSAGE);                                                            
             }
            else{
                JOptionPane.showMessageDialog(null, "No Existe el usuario","Informacion", JOptionPane.INFORMATION_MESSAGE);                                            
            }
        }
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        int fila = Tablausuarios.getSelectedRow();
        if (fila <0){
            JOptionPane.showMessageDialog(null, "Por favor seleccione una Fila","Informacion", JOptionPane.INFORMATION_MESSAGE);                        
        }
        else
        {
            int a = JOptionPane.showConfirmDialog(null, "Esta seguro de borrar el usuario " +  Tablausuarios.getValueAt(fila,0)+ "?", "Select",JOptionPane.YES_NO_OPTION);                        
            if (a==0){
                String usuario = (String) Tablausuarios.getValueAt(fila,0);
                String nombre =  (String) Tablausuarios.getValueAt(fila,1);
                String correo =  (String) Tablausuarios.getValueAt(fila,2);        
                int telefono = Integer.parseInt((String) Tablausuarios.getValueAt(fila,3).toString());                
                UserEmploy p5 = new UserEmploy (usuario,"",nombre, correo, telefono);
                try {
                    p5.BorrarUsuario();
                } catch (SQLException ex) {
                    Logger.getLogger(PanelUsers.class.getName()).log(Level.SEVERE, null, ex);
                }
                FillTableUsers();                    
                txtnombre.setText("");
                txtusuario.setText("");
                txtcorreo.setText("");
                txttelefono.setText("");
                JOptionPane.showMessageDialog(null, "Uusario Borrado","Informacion", JOptionPane.INFORMATION_MESSAGE);                                                            
            }
        }
                
    }//GEN-LAST:event_btnBorrarActionPerformed

                        
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        
        txtnombre.setText("");
        txtusuario.setText("");
        txtcorreo.setText("");
        txttelefono.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassActionPerformed

    private void TablausuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablausuariosMouseClicked
        // TODO add your handling code here:
    int fila = Tablausuarios.getSelectedRow();
    if (fila == -1){
            JOptionPane.showMessageDialog(null, "Por favor seleccione una Fila","Informacion", JOptionPane.INFORMATION_MESSAGE);                        
        }   else{
        
	String usuario = (String) Tablausuarios.getValueAt(fila,0);
	String nombre =  (String) Tablausuarios.getValueAt(fila,1);
        String correo =  (String) Tablausuarios.getValueAt(fila,2);        
	int telefono = Integer.parseInt((String) Tablausuarios.getValueAt(fila,3).toString());
        txtnombre.setText(nombre);
        txtusuario.setText(usuario);
        txtcorreo.setText(correo);
        txttelefono.setText(""+telefono);
        
    }
        
    }//GEN-LAST:event_TablausuariosMouseClicked

    private void PageConfigFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PageConfigFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_PageConfigFocusGained

    private void txttelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros)
        {
            evt.consume();
        }

        if (txttelefono.getText().trim().length() == 10) {
            evt.consume();
        }        
    }//GEN-LAST:event_txttelefonoKeyTyped

    private void txtusuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusuarioKeyTyped
        // TODO add your handling code here:
        if (txtusuario.getText().length() >= 8)
        {
            evt.consume();
        }

    }//GEN-LAST:event_txtusuarioKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PageConfig;
    private javax.swing.JTable Tablausuarios;
    private javax.swing.JButton bntInsertar;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblcorreo;
    private javax.swing.JLabel lblpass;
    private javax.swing.JLabel lbltelefono;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtpass;
    private javax.swing.JTextField txttelefono;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
